require 'bundler/setup'

require 'albacore'
require 'albacore/tasks/versionizer'
require 'albacore/ext/teamcity'

Albacore::Tasks::Versionizer.new :versioning

desc 'Restore paket.exe'
task :restore_paket do
  system 'tools/paket.bootstrapper.exe', clr_command: true
end

desc 'Restore all packages'
task :restore => [:restore_paket] do
  system 'tools/paket.exe', 'restore', clr_command: true
end


desc 'Perform fast build (warn: doesn\'t d/l deps)'
build :compile_quick do |b|
  b.logging = 'detailed'
  b.sln     = 'source/Thinktecture.IdentityServer.v3.sln'
end

desc 'restore all nugets as per the packages.config files'
nugets_restore :restore do |p|
  p.out = 'src/packages'
  p.exe = 'tools/NuGet.exe'
end

desc 'Perform full build'
build :compile => [:versioning, :restore] do |b|
  b.sln = 'source/Thinktecture.IdentityServer.v3.sln'
end

task :default => :compile
